#!/usr/bin/env bash
# =============================================================================
#  Module 30 — Memcached
#  In-memory key-value cache — alternative to Redis for pure caching workloads.
#  Run standalone: sudo bash modules/30-memcached.sh
# =============================================================================
set -euo pipefail

if [[ -z "${SETUP_LOADED:-}" ]]; then
  _D="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
  _BASE="$(dirname "$_D")"
  [[ -f "${_BASE}/config.sh" ]] && source "${_BASE}/config.sh"
  _src() {
    local f="$1"
    if [[ -f "${_BASE}/lib/${f}" ]]; then source "${_BASE}/lib/${f}"; else
      local t
      t=$(mktemp)
      curl -fsSL "${SETUP_BASE_URL}/lib/${f}" -o "$t" && source "$t"
      rm -f "$t"
    fi
  }
  _src colors.sh
  _src prompts.sh
  _src creds.sh
  _src utils.sh
  export SETUP_LOADED=1
fi

module_header "Memcached" "Fast in-memory cache — configure as Laravel's CACHE_STORE driver."
require_root

PHP_VERSION="$(creds_load PHP_VERSION 2> /dev/null || echo "8.4")"
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/ {print $2}')
DEFAULT_MEM=$((TOTAL_RAM_MB / 8))
[[ $DEFAULT_MEM -lt 64 ]] && DEFAULT_MEM=64
[[ $DEFAULT_MEM -gt 512 ]] && DEFAULT_MEM=512

if has_cmd memcached; then
  CURRENT_VER=$(memcached --version 2>&1 | head -1)
  warn "Memcached already installed: ${CURRENT_VER}"
  ask_choice EXISTING_MODE "Memcached detected — what to do?" \
    "Reconfigure only" \
    "Reinstall" \
    "Skip this module"
  case "$EXISTING_MODE" in
    "Skip"*)
      info "Skipping."
      exit 0
      ;;
    "Reinstall"*) : ;;
    *) SKIP_INSTALL=true ;;
  esac
fi

ask MEMCACHED_MEMORY "Memory limit (MB)" "${DEFAULT_MEM}"
ask MEMCACHED_PORT "Memcached port" "11211"
ask MEMCACHED_CONNS "Max simultaneous connections" "1024"

echo
info "Server: ${TOTAL_RAM_MB}MB RAM — allocating ${MEMCACHED_MEMORY}MB to Memcached"
echo
confirm_or_exit "Install Memcached?"

# Install
if [[ "${SKIP_INSTALL:-false}" != "true" ]]; then
  step "Installing Memcached..."
  pkg_install memcached
  success "Memcached installed."
fi

# Configure
step "Configuring Memcached..."
MEMCACHED_CONF="/etc/memcached.conf"
if [[ -f "$MEMCACHED_CONF" ]]; then
  backup_file "$MEMCACHED_CONF"
  tmp=$(mktemp)
  sed \
    -e "s/^-m [0-9]*/-m ${MEMCACHED_MEMORY}/" \
    -e "s/^-p [0-9]*/-p ${MEMCACHED_PORT}/" \
    -e "s/^-c [0-9]*/-c ${MEMCACHED_CONNS}/" \
    "$MEMCACHED_CONF" > "$tmp" && mv "$tmp" "$MEMCACHED_CONF"
else
  cat > /etc/memcached.conf << EOF
# Memcached configuration — generated by laravel-server-setup
-d
-m ${MEMCACHED_MEMORY}
-p ${MEMCACHED_PORT}
-u memcache
-l 127.0.0.1
-c ${MEMCACHED_CONNS}
-P /var/run/memcached/memcached.pid
EOF
fi

systemctl enable memcached --quiet
systemctl restart memcached
success "Memcached running on port ${MEMCACHED_PORT} with ${MEMCACHED_MEMORY}MB."

# PHP extension
step "Installing PHP Memcached extension (php${PHP_VERSION}-memcached)..."
pkg_install "php${PHP_VERSION}-memcached" 2> /dev/null && {
  systemctl restart "php${PHP_VERSION}-fpm" 2> /dev/null || true
  success "php${PHP_VERSION}-memcached installed."
} || warn "Could not install php${PHP_VERSION}-memcached — install manually."

creds_section "Memcached"
creds_save "MEMCACHED_HOST" "127.0.0.1"
creds_save "MEMCACHED_PORT" "$MEMCACHED_PORT"
creds_save "MEMCACHED_MEMORY" "${MEMCACHED_MEMORY}MB"

echo
success "Memcached module complete."
info "Laravel .env values:"
dim "CACHE_STORE=memcached"
dim "MEMCACHED_HOST=127.0.0.1"
dim "MEMCACHED_PORT=${MEMCACHED_PORT}"
