#!/usr/bin/env bash
# =============================================================================
#  Module — Automated Backups (Database + Files)
#  Run standalone: sudo bash modules/backups.sh
# =============================================================================
set -euo pipefail

if [[ -z "${SETUP_LOADED:-}" ]]; then
  _D="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
  _BASE="$(dirname "$_D")"
  # Source config for SETUP_BASE_URL
  [[ -f "${_BASE}/config.sh" ]] && source "${_BASE}/config.sh"
  _src() {
    local f="$1"
    if [[ -f "${_BASE}/lib/${f}" ]]; then source "${_BASE}/lib/${f}"; else
      local t
      t=$(mktemp)
      curl -fsSL "${SETUP_BASE_URL}/lib/${f}" -o "$t" && source "$t"
      rm -f "$t"
    fi
  }
  _src colors.sh
  _src prompts.sh
  _src creds.sh
  _src utils.sh
  export SETUP_LOADED=1
else
  # Called from larakit CLI or setup.sh — source libs from SETUP_BASE_DIR
  source "${SETUP_BASE_DIR}/lib/colors.sh"
  source "${SETUP_BASE_DIR}/lib/prompts.sh"
  source "${SETUP_BASE_DIR}/lib/creds.sh"
  source "${SETUP_BASE_DIR}/lib/utils.sh"
fi

module_header "Automated Backups" "Daily DB dumps + file backups with configurable retention and optional remote upload."
require_root

# Config
DB_NAME="$(creds_load DB_NAME 2> /dev/null || echo "")"
DB_USER="$(creds_load DB_USER 2> /dev/null || echo "")"
DB_PASSWORD="$(creds_load DB_PASSWORD 2> /dev/null || echo "")"
APP_PATH="$(creds_load APP_PATH 2> /dev/null || echo "")"
DEPLOY_USER="$(creds_load DEPLOY_USER 2> /dev/null || echo "deploy")"

ask BACKUP_DIR "Local backup directory" "/var/backups/laravel"
ask DB_NAME "Database name" "${DB_NAME:-}"
ask DB_USER "Database user" "${DB_USER:-}"
ask_secret DB_PASS_INPUT "Database password (blank to use saved)"
[[ -n "$DB_PASS_INPUT" ]] && DB_PASSWORD="$DB_PASS_INPUT"
ask APP_PATH "App directory to back up" "${APP_PATH:-}"
ask RETENTION_DAYS "Keep backups for N days" "14"
ask BACKUP_HOUR "Backup hour (0-23, 24h)" "2"

# Remote storage
ask_choice REMOTE_STORAGE "Remote storage for backups:" \
  "None (local only)" \
  "S3 / MinIO (via AWS CLI)" \
  "Backblaze B2 (via rclone)" \
  "SFTP / rsync (via rsync)"

if [[ "$REMOTE_STORAGE" == "S3"* ]]; then
  ask S3_BUCKET "S3 bucket name (s3://bucket/path)" ""
  ask S3_ENDPOINT "S3 endpoint URL (blank for AWS)" ""
  ask S3_ACCESS_KEY "AWS_ACCESS_KEY_ID" ""
  ask_secret S3_SECRET_KEY "AWS_SECRET_ACCESS_KEY"
elif [[ "$REMOTE_STORAGE" == "SFTP"* ]]; then
  ask RSYNC_DEST "rsync destination (user@host:/path)" ""
fi

# Notifications
ask_yn NOTIFY_ON_FAIL "Send email notification on backup failure?" "n"
if [[ "$NOTIFY_ON_FAIL" == "true" ]]; then
  ask NOTIFY_EMAIL "Notification email" ""
fi

echo
confirm_or_exit "Set up automated backups?"

mkdir -p "$BACKUP_DIR"
chmod 700 "$BACKUP_DIR"

# Install tools
step "Installing backup tools..."
pkg_install gzip pigz pv

if [[ "$REMOTE_STORAGE" == "S3"* ]]; then
  has_cmd aws || pkg_install awscli
elif [[ "$REMOTE_STORAGE" == "Backblaze"* ]]; then
  has_cmd rclone || {
    curl -fsSL https://rclone.org/install.sh | bash > /dev/null 2>&1
  }
fi

# Create backup script
step "Creating backup script..."
cat > /usr/local/bin/laravel-backup << SCRIPT
#!/usr/bin/env bash
# Laravel backup script — generated by laravel-server-setup
set -euo pipefail

BACKUP_DIR="${BACKUP_DIR}"
DATE=\$(date +%Y-%m-%d_%H-%M-%S)
LOG="${BACKUP_DIR}/backup.log"

log() { echo "[\$(date '+%Y-%m-%d %H:%M:%S')] \$*" | tee -a "\$LOG"; }
error() { log "ERROR: \$*"; $([ "$NOTIFY_ON_FAIL" == "true" ] && echo "echo \"\$*\" | mail -s 'Backup Failed' ${NOTIFY_EMAIL:-root}" || echo "true"); exit 1; }

log "=== Backup started ==="

# Database
DB_FILE="\${BACKUP_DIR}/db_${DB_NAME}_\${DATE}.sql.gz"
log "Dumping database '${DB_NAME}'..."
mysqldump --user="${DB_USER}" --password="${DB_PASSWORD}" \\
  --single-transaction --quick --lock-tables=false \\
  --routines --triggers \\
  "${DB_NAME}" | pigz -c > "\$DB_FILE" || error "Database dump failed"
log "Database backup: \$DB_FILE (\$(du -sh \$DB_FILE | cut -f1))"

# App files
$(if [[ -n "$APP_PATH" ]]; then
  cat << 'APPBACKUP'
APP_FILE="${BACKUP_DIR}/app_${DATE}.tar.gz"
log "Archiving app storage..."
tar -czf "$APP_FILE" --exclude="*/node_modules" --exclude="*/.git" \
  -C "$(dirname ${APP_PATH})" "$(basename ${APP_PATH})/storage" 2> /dev/null || true
log "App backup: $APP_FILE ($(du -sh $APP_FILE 2> /dev/null | cut -f1 || echo '?'))"
APPBACKUP
fi)

# Remote upload
$(if [[ "$REMOTE_STORAGE" == "S3"* ]]; then
  cat << S3BLOCK
log "Uploading to S3..."
export AWS_ACCESS_KEY_ID="${S3_ACCESS_KEY}"
export AWS_SECRET_ACCESS_KEY="${S3_SECRET_KEY}"
S3_OPTS=""
[[ -n "${S3_ENDPOINT:-}" ]] && S3_OPTS="--endpoint-url ${S3_ENDPOINT}"
aws s3 cp "\$DB_FILE" "${S3_BUCKET}/\$(basename \$DB_FILE)" \$S3_OPTS || error "S3 upload failed"
[[ -f "\${APP_FILE:-}" ]] && aws s3 cp "\$APP_FILE" "${S3_BUCKET}/\$(basename \$APP_FILE)" \$S3_OPTS || true
log "Remote upload complete."
S3BLOCK
elif [[ "$REMOTE_STORAGE" == "SFTP"* ]]; then
  cat << RSYNCBLOCK
log "Syncing to remote via rsync..."
rsync -az --delete "\$BACKUP_DIR/" "${RSYNC_DEST}/" || error "rsync failed"
log "Remote sync complete."
RSYNCBLOCK
fi)

# Cleanup old backups
log "Cleaning up backups older than ${RETENTION_DAYS} days..."
find "\$BACKUP_DIR" -name "*.sql.gz" -mtime +${RETENTION_DAYS} -delete
find "\$BACKUP_DIR" -name "*.tar.gz" -mtime +${RETENTION_DAYS} -delete

log "=== Backup complete ==="
SCRIPT

chmod +x /usr/local/bin/laravel-backup
success "Backup script created: /usr/local/bin/laravel-backup"

# Cron job
step "Adding backup cron job..."
CRON_LINE="${BACKUP_HOUR} 0 * * * /usr/local/bin/laravel-backup >> ${BACKUP_DIR}/backup.log 2>&1"
(
  crontab -u root -l 2> /dev/null
  echo "$CRON_LINE"
) | sort -u | crontab -u root -
success "Backup scheduled daily at ${BACKUP_HOUR}:00."

# Test run
ask_yn TEST_RUN "Run a backup test now?" "y"
if [[ "$TEST_RUN" == "true" ]]; then
  step "Running backup test..."
  if /usr/local/bin/laravel-backup; then
    success "Test backup completed."
    ls -lh "${BACKUP_DIR}"/*.sql.gz 2> /dev/null | tail -3
  else
    warn "Test backup failed — check credentials and paths."
  fi
fi

# Save
creds_section "Backups"
creds_save "BACKUP_DIR" "$BACKUP_DIR"
creds_save "BACKUP_SCHEDULE" "Daily at ${BACKUP_HOUR}:00"
creds_save "BACKUP_RETENTION" "${RETENTION_DAYS} days"
creds_save "BACKUP_SCRIPT" "/usr/local/bin/laravel-backup"
[[ -n "${S3_BUCKET:-}" ]] && creds_save "BACKUP_REMOTE" "$S3_BUCKET"
[[ -n "${RSYNC_DEST:-}" ]] && creds_save "BACKUP_REMOTE" "$RSYNC_DEST"

echo
success "Backup module complete."
info "Manual backup: laravel-backup"
dim "Logs: ${BACKUP_DIR}/backup.log"
