#!/usr/bin/env bash
# =============================================================================
#  Module 25 — Performance Tuning
#  Optimizes sysctl, PHP-FPM pools, Nginx workers, and MySQL for production
#  Run standalone: sudo bash modules/25-tuning.sh
# =============================================================================
set -euo pipefail

if [[ -z "${SETUP_LOADED:-}" ]]; then
  _D="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
  _BASE="$(dirname "$_D")"
  # Source config for SETUP_BASE_URL
  [[ -f "${_BASE}/config.sh" ]] && source "${_BASE}/config.sh"
  _src() {
    local f="$1"
    if [[ -f "${_BASE}/lib/${f}" ]]; then source "${_BASE}/lib/${f}"; else
      local t
      t=$(mktemp)
      curl -fsSL "${SETUP_BASE_URL}/lib/${f}" -o "$t" && source "$t"
      rm -f "$t"
    fi
  }
  _src colors.sh
  _src prompts.sh
  _src creds.sh
  _src utils.sh
  export SETUP_LOADED=1
else
  # Called from larakit CLI or setup.sh — source libs from SETUP_BASE_DIR
  source "${SETUP_BASE_DIR}/lib/colors.sh"
  source "${SETUP_BASE_DIR}/lib/prompts.sh"
  source "${SETUP_BASE_DIR}/lib/creds.sh"
  source "${SETUP_BASE_DIR}/lib/utils.sh"
fi

module_header "Performance Tuning" "Tunes PHP-FPM, Nginx, MySQL/MariaDB, and Linux kernel for production workloads."
require_root

# System info
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/ {print $2}')
CPU_CORES=$(nproc)
PHP_VERSION="$(creds_load PHP_VERSION 2> /dev/null || echo "8.4")"

info "Server specs: ${TOTAL_RAM_MB}MB RAM, ${CPU_CORES} CPU cores"

ask_choice TUNE_PROFILE "Tuning profile:" \
  "Low traffic    (≤ 100 concurrent users, ≤ 1GB RAM)" \
  "Medium traffic (≤ 500 concurrent users, 1-4GB RAM)" \
  "High traffic   (500+ concurrent users, 4GB+ RAM)"

echo
info "Will tune:"
dim "• Linux kernel (sysctl) — TCP, file descriptors, network buffers"
dim "• PHP-FPM pool — worker count based on RAM"
dim "• Nginx — worker processes and connections"
dim "• MySQL/MariaDB — InnoDB buffer pool, connections"
echo
confirm_or_exit "Apply performance tuning?"

# Profile values
case "${TUNE_PROFILE}" in
  "Low traffic"*)
    PHP_MAX_CHILDREN=10
    PHP_MIN_SPARE=2
    PHP_MAX_SPARE=4
    PHP_MAX_REQUESTS=200
    NGINX_WORKERS="$CPU_CORES"
    NGINX_CONNECTIONS=512
    MYSQL_BUFFER_POOL_MB=$((TOTAL_RAM_MB / 4))
    ;;
  "Medium traffic"*)
    PHP_MAX_CHILDREN=30
    PHP_MIN_SPARE=5
    PHP_MAX_SPARE=10
    PHP_MAX_REQUESTS=500
    NGINX_WORKERS="$CPU_CORES"
    NGINX_CONNECTIONS=1024
    MYSQL_BUFFER_POOL_MB=$((TOTAL_RAM_MB / 3))
    ;;
  "High traffic"*)
    PHP_MAX_CHILDREN=60
    PHP_MIN_SPARE=10
    PHP_MAX_SPARE=20
    PHP_MAX_REQUESTS=1000
    NGINX_WORKERS="auto"
    NGINX_CONNECTIONS=2048
    MYSQL_BUFFER_POOL_MB=$((TOTAL_RAM_MB / 2))
    ;;
esac

# Linux kernel (sysctl)
step "Tuning Linux kernel..."
cat > /etc/sysctl.d/99-laravel-tuning.conf << EOF
# Laravel server tuning — generated by laravel-server-setup

# TCP performance
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65535
net.ipv4.tcp_max_syn_backlog = 65535
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.ip_local_port_range = 1024 65535

# Memory and file descriptors
fs.file-max = 2097152
vm.swappiness = 10
vm.vfs_cache_pressure = 50
vm.overcommit_memory = 1

# Network buffers
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
EOF

sysctl -p /etc/sysctl.d/99-laravel-tuning.conf > /dev/null
success "Kernel tuning applied."

# System file descriptor limits
step "Raising file descriptor limits..."
cat > /etc/security/limits.d/laravel.conf << EOF
* soft nofile 65536
* hard nofile 131072
www-data soft nofile 65536
www-data hard nofile 131072
EOF

ensure_line "session required pam_limits.so" /etc/pam.d/common-session
ensure_line "DefaultLimitNOFILE=65536" /etc/systemd/system.conf
ensure_line "DefaultLimitNOFILE=65536" /etc/systemd/user.conf
systemctl daemon-reload
success "File descriptor limits raised to 65536."

# PHP-FPM pool tuning
step "Tuning PHP-FPM pool..."
FPM_POOL_CONF="/etc/php/${PHP_VERSION}/fpm/pool.d/www.conf"
if [[ -f "$FPM_POOL_CONF" ]]; then
  backup_file "$FPM_POOL_CONF"
  tmp=$(mktemp)
  sed \
    -e "s/^pm = .*/pm = dynamic/" \
    -e "s/^pm.max_children = .*/pm.max_children = ${PHP_MAX_CHILDREN}/" \
    -e "s/^pm.start_servers = .*/pm.start_servers = ${PHP_MIN_SPARE}/" \
    -e "s/^pm.min_spare_servers = .*/pm.min_spare_servers = ${PHP_MIN_SPARE}/" \
    -e "s/^pm.max_spare_servers = .*/pm.max_spare_servers = ${PHP_MAX_SPARE}/" \
    -e "s/^;*pm.max_requests = .*/pm.max_requests = ${PHP_MAX_REQUESTS}/" \
    -e "s|^;pm.status_path.*|pm.status_path = /fpm-status|" \
    "$FPM_POOL_CONF" > "$tmp" && mv "$tmp" "$FPM_POOL_CONF"
  systemctl restart "php${PHP_VERSION}-fpm"
  success "PHP-FPM tuned (max_children: ${PHP_MAX_CHILDREN}, dynamic)."
else
  warn "PHP-FPM pool config not found at ${FPM_POOL_CONF} — skipping."
fi

# Nginx tuning
step "Tuning Nginx..."
NGINX_CONF="/etc/nginx/nginx.conf"
backup_file "$NGINX_CONF"

cat > /etc/nginx/conf.d/performance.conf << EOF
# Nginx performance tuning — generated by laravel-server-setup
worker_rlimit_nofile 65536;

events {
    worker_connections ${NGINX_CONNECTIONS};
    use epoll;
    multi_accept on;
}

http {
    # Connection timeouts
    keepalive_timeout 65;
    keepalive_requests 100;
    client_header_timeout 15;
    client_body_timeout 15;
    send_timeout 15;

    # Buffer sizes
    client_body_buffer_size 128k;
    client_max_body_size 64m;
    client_header_buffer_size 1k;
    large_client_header_buffers 4 16k;
    output_buffers 1 32k;
    postpone_output 1460;

    # Open file cache
    open_file_cache max=10000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;
}
EOF

tmp=$(mktemp)
sed "s/worker_processes .*/worker_processes ${NGINX_WORKERS};/" "$NGINX_CONF" > "$tmp" && mv "$tmp" "$NGINX_CONF"
nginx -t && systemctl reload nginx
success "Nginx tuned (workers: ${NGINX_WORKERS}, connections: ${NGINX_CONNECTIONS})."

# MySQL tuning
if has_cmd mysql; then
  step "Tuning MySQL/MariaDB..."
  cat > /etc/mysql/conf.d/99-laravel-performance.cnf << EOF
[mysqld]
# InnoDB
innodb_buffer_pool_size = ${MYSQL_BUFFER_POOL_MB}M
innodb_buffer_pool_instances = $((MYSQL_BUFFER_POOL_MB > 1024 ? 4 : 1))
innodb_log_file_size = 256M
innodb_log_buffer_size = 64M
innodb_flush_log_at_trx_commit = 2
innodb_flush_method = O_DIRECT
innodb_file_per_table = 1
innodb_read_io_threads = $((CPU_CORES > 4 ? CPU_CORES / 2 : 2))
innodb_write_io_threads = $((CPU_CORES > 4 ? CPU_CORES / 2 : 2))

# Connections
max_connections = 200
thread_cache_size = 32
table_open_cache = 2000
table_definition_cache = 1024

# Query cache (disabled — use Redis instead)
query_cache_type = 0
query_cache_size = 0

# Slow query log
slow_query_log = 1
slow_query_log_file = /var/log/mysql/slow.log
long_query_time = 1

# Temp tables
tmp_table_size = 64M
max_heap_table_size = 64M

# MyISAM (minimal — we use InnoDB)
key_buffer_size = 32M
EOF

  DB_SERVICE="$(creds_load DB_SERVICE 2> /dev/null || echo "mysql")"
  systemctl restart "$DB_SERVICE"
  success "MySQL tuned (InnoDB buffer: ${MYSQL_BUFFER_POOL_MB}MB)."
fi

# Redis tuning
if has_cmd redis-cli; then
  step "Tuning Redis for production..."
  # Already done in module 06, but add latency monitor
  redis-cli CONFIG SET latency-tracking yes 2> /dev/null || true
  success "Redis production settings verified."
fi

creds_section "Tuning"
creds_save "TUNE_PROFILE" "${TUNE_PROFILE%% *}"
creds_save "PHP_FPM_MAX_CHILDREN" "$PHP_MAX_CHILDREN"
creds_save "NGINX_WORKER_CONNECTIONS" "$NGINX_CONNECTIONS"
creds_save "MYSQL_BUFFER_POOL_MB" "$MYSQL_BUFFER_POOL_MB"

echo
success "Performance tuning complete."
info "Verify with: php artisan about"
